# Generated by Django 3.2.7 on 2021-09-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
    ]
