# Generated by Django 3.2.7 on 2021-09-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_homework_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-created',)},
        ),
    ]
